### ISSUE TITLE
Conflict with AMP

### ISSUE THREAD

**Issue by abdallahk** [pcfreak30/rocket-footer-js#3]
First of all, this is a great project and I appreciate all the hard work, Derrik.

Since AMP pages require the includes (JS, CSS etc) in the header, this plugin messes up the by placing them in the footer. Find a bypass for AMP plugins such as:

- WP AMP (https://codecanyon.net/item/wp-amp-accelerated-mobile-pages-for-wordpress-and-woocommerce/16278608 | I can provide a copy if needed)
- AMP for WordPress (https://wordpress.org/plugins/amp/)
- AMP for WP (https://wordpress.org/plugins/accelerated-mobile-pages/)

**Comment by pcfreak30** [comment]
Thanks, this should not even be running for AMP anyways.
