### ISSUE TITLE
Unexpected token ; with WooCommerce Google Analytics Integration

### ISSUE THREAD

**Issue by thenathantt** [pcfreak30/rocket-footer-js#4]
I receive Uncaught SyntaxError: Unexpected token ; when I have the plugin enabled with WooCommerce Google Analytics Integration. The ; seems to be at the end of the script

`ga( 'require', 'ec' ); . . . z(function(){Z.D(["provide","render",ua])});function La(a){var b=1,c;if(a)for(b=0,c=a.length-1;0<=c;c--){var d=a.charCodeAt(c);b=(b<<6&268435455)+d+(d<<14);d=b&266338304;b=0!=d?b^d>>21:b}return b};})(window);
IiI=;`

**Comment by pcfreak30** [comment]
Temporary workaround until I can resolve this.

```
add_filter('rocket_footer_js_rewrite_manager_modules', function($modules){
	$modules = array_flip($modules);
	if(isset($modules['GoogleAnalytics'])){
		unset(isset($modules['GoogleAnalytics']);
	}
	return array_keys($modules);
});
```

Add this to mu-plugins. it will disable processing of that script. Alternatively, manually add the script without a plugin and it may work or add data-no-minify="1" onto the script tag.

**Comment by thenathantt** [comment]
Gave it a try but it seems to be making my site crash. Unfortunately I can't add the tag manually as it's an eCommerce store and have the GA WooCommerce Plugin sending back data.

**Comment by pcfreak30** [comment]
Sorry, I kind of wrote it without any syntax checking :P.

Try this:

```
add_filter( 'rocket_footer_js_rewrite_manager_modules', function ( $modules ) {
	$modules = array_flip( $modules );
	if ( isset( $modules['GoogleAnalytics'] ) ) {
		unset( $modules['GoogleAnalytics'] );
	}

	return array_keys( $modules );
} );
```

Verified it in PHPStorm.

**Comment by thenathantt** [comment]
Great, seems to be working. FYI, once GA was fixed, ran into an issue with Facebook Pixel, `variable n undefined` so I had to exclude that as well.

**Comment by pcfreak30** [comment]
@thenathantt this hack can be removed. i just pushed out a bug fix for for this and it was not specific to GA
